#ifndef ERRORS_V
#define ERRORS_V
char errors[8][30]  = {
    "",
    "MALLOC_EXCEPTION",
    "RETRY_EXCEPTION",
    "ILLEGAL_ARGUMENT_EXCEPTION",
    "ILLEGAL_STATE_EXCEPTION",
    "INDEX_OUT_OF_BOUNDS_EXCEPTION",
    "NULL_POINTER_EXCEPTION",
    "TEST_FAILED_EXCEPTION"
};
#endif